name: Commit Message

on: [push]

jobs:
  print-commit-message:
    runs-on: ubuntu-latest
    steps:
    - name: log commit message
      run: echo '${{ toJSON(github.event.commits[0].message) }}'
      shell: bash
