name: Commit Message

on: 
  push

jobs:
  print-commit-message:
    runs-on: ubuntu-latest
    steps:
    - name: log commit message
      run: echo '${{ toJson{github.event}}' | jq
      shell: bash
