name: Commit Message

on: 
  commit:

jobs:
  print-commit-message:
    run-on: ubuntu-latest:
    steps:
    - name: "log commit message"
      run: echo '${{ toJson{github.event}}}' | jq
      shell: bash
