name: Commit Message

on: 
  branch_protection_rule

jobs:
  print-commit-message:
    runs-on: ubuntu-latest
    steps:
    - name: log commit message
      run: echo '${{ toJson{github.event}}}' | jq
      shell: bash
